theme: jekyll-theme-hacker
title: Sid's Main Page
description: This is Siddhant's website. I think I publish my work here. I am not entirely sure why I created this website and what I want out of it. 
